---
development:
  DB_FILENAME: app/infrastructure/database/local/dev.db
  api_key: SCOPUS_API_TOKEN
  API_HOST: http://localhost:9292

test:
  DB_FILENAME: app/infrastructure/database/local/test.db
  api_key: SCOPUS_API_TOKEN
  API_HOST: http://localhost:9292
